export const CountryData = [
  { id: 1, code: "AD", name: "Andorra" },
  { id: 2, code: "AE", name: "United Arab Emirates" },
  { id: 3, code: "AF", name: "Afghanistan" },
  { id: 4, code: "AG", name: "Antigua and Barbuda" },
  { id: 5, code: "AI", name: "Anguilla" },
  { id: 6, code: "AL", name: "Albania" },
  { id: 7, code: "AM", name: "Armenia" },
  { id: 8, code: "AO", name: "Angola" },
  { id: 9, code: "AQ", name: "Antarctica" },
  { id: 10, code: "AR", name: "Argentina" },
  { id: 11, code: "AS", name: "American Samoa" },
  { id: 12, code: "AT", name: "Austria" },
  { id: 13, code: "AU", name: "Australia" },
  { id: 14, code: "AW", name: "Aruba" },
  { id: 15, code: "AX", name: "Åland Islands" },
  { id: 16, code: "AZ", name: "Azerbaijan" },
  { id: 17, code: "BA", name: "Bosnia and Herzegovina" },
  { id: 18, code: "BB", name: "Barbados" },
  { id: 19, code: "BD", name: "Bangladesh" },
  { id: 20, code: "BE", name: "Belgium" },
  { id: 21, code: "BF", name: "Burkina Faso" },
  { id: 22, code: "BG", name: "Bulgaria" },
  { id: 23, code: "BH", name: "Bahrain" },
  { id: 24, code: "BI", name: "Burundi" },
  { id: 25, code: "BJ", name: "Benin" },
  { id: 26, code: "BL", name: "Saint Barthélemy" },
  { id: 27, code: "BM", name: "Bermuda" },
  { id: 28, code: "BN", name: "Brunei Darussalam" },
  { id: 29, code: "BO", name: "Bolivia (Plurinational State of)" },
  { id: 30, code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { id: 31, code: "BR", name: "Brazil" },
  { id: 32, code: "BS", name: "Bahamas" },
  { id: 33, code: "BT", name: "Bhutan" },
  { id: 34, code: "BV", name: "Bouvet Island" },
  { id: 35, code: "BW", name: "Botswana" },
  { id: 36, code: "BY", name: "Belarus" },
  { id: 37, code: "BZ", name: "Belize" },
  { id: 38, code: "CA", name: "Canada" },
  { id: 39, code: "CC", name: "Cocos (Keeling) Islands" },
  { id: 40, code: "CD", name: "Congo (Democratic Republic of the)" },
  { id: 41, code: "CF", name: "Central African Republic" },
  { id: 42, code: "CG", name: "Congo" },
  { id: 43, code: "CH", name: "Switzerland" },
  { id: 44, code: "CI", name: "Côte d'Ivoire" },
  { id: 45, code: "CK", name: "Cook Islands" },
  { id: 46, code: "CL", name: "Chile" },
  { id: 47, code: "CM", name: "Cameroon" },
  { id: 48, code: "CN", name: "China" },
  { id: 49, code: "CO", name: "Colombia" },
  { id: 50, code: "CR", name: "Costa Rica" },
  { id: 51, code: "CU", name: "Cuba" },
  { id: 52, code: "CV", name: "Cabo Verde" },
  { id: 53, code: "CW", name: "Curaçao" },
  { id: 54, code: "CX", name: "Christmas Island" },
  { id: 55, code: "CY", name: "Cyprus" },
  { id: 56, code: "CZ", name: "Czech Republic" },
  { id: 57, code: "DE", name: "Germany" },
  { id: 58, code: "DJ", name: "Djibouti" },
  { id: 59, code: "DK", name: "Denmark" },
  { id: 60, code: "DM", name: "Dominica" },
  { id: 61, code: "DO", name: "Dominican Republic" },
  { id: 62, code: "DZ", name: "Algeria" },
  { id: 63, code: "EC", name: "Ecuador" },
  { id: 64, code: "EE", name: "Estonia" },
  { id: 65, code: "EG", name: "Egypt" },
  { id: 66, code: "EH", name: "Western Sahara" },
  { id: 67, code: "ER", name: "Eritrea" },
  { id: 68, code: "ES", name: "Spain" },
  { id: 69, code: "ET", name: "Ethiopia" },
  { id: 70, code: "FI", name: "Finland" },
  { id: 71, code: "FJ", name: "Fiji" },
  { id: 72, code: "FK", name: "Falkland Islands" },
  { id: 74, code: "FO", name: "Faroe Islands" },
  { id: 75, code: "FR", name: "France" },
  { id: 76, code: "GA", name: "Gabon" },
  { id: 77, code: "GB", name: "United Kingdom" },
  { id: 78, code: "GD", name: "Grenada" },
  { id: 79, code: "GE", name: "Georgia" },
  { id: 80, code: "GF", name: "French Guiana" },
  { id: 81, code: "GG", name: "Guernsey" },
  { id: 82, code: "GH", name: "Ghana" },
  { id: 83, code: "GI", name: "Gibraltar" },
  { id: 84, code: "GL", name: "Greenland" },
  { id: 85, code: "GM", name: "Gambia" },
  { id: 86, code: "GN", name: "Guinea" },
  { id: 87, code: "GP", name: "Guadeloupe" },
  { id: 88, code: "GQ", name: "Equatorial Guinea" },
  { id: 89, code: "GR", name: "Greece" },
  { id: 91, code: "GT", name: "Guatemala" },
  { id: 92, code: "GU", name: "Guam" },
  { id: 93, code: "GW", name: "Guinea-Bissau" },
  { id: 94, code: "GY", name: "Guyana" },
  { id: 95, code: "HK", name: "Hong Kong" },
  { id: 97, code: "HN", name: "Honduras" },
  { id: 98, code: "HR", name: "Croatia" },
  { id: 99, code: "HT", name: "Haiti" },
  { id: 100, code: "HU", name: "Hungary" },
  { id: 101, code: "ID", name: "Indonesia" },
  { id: 102, code: "IE", name: "Ireland" },
  { id: 103, code: "IL", name: "Israel" },
  { id: 104, code: "IM", name: "Isle of Man" },
  { id: 105, code: "IN", name: "India" },
  { id: 107, code: "IQ", name: "Iraq" },
  { id: 108, code: "IR", name: "Iran" },
  { id: 109, code: "IS", name: "Iceland" },
  { id: 110, code: "IT", name: "Italy" },
  { id: 111, code: "JE", name: "Jersey" },
  { id: 112, code: "JM", name: "Jamaica" },
  { id: 113, code: "JO", name: "Jordan" },
  { id: 114, code: "JP", name: "Japan" },
  { id: 115, code: "KE", name: "Kenya" },
  { id: 116, code: "KG", name: "Kyrgyzstan" },
  { id: 117, code: "KH", name: "Cambodia" },
  { id: 118, code: "KI", name: "Kiribati" },
  { id: 119, code: "KM", name: "Comoros" },
  { id: 120, code: "KN", name: "Saint Kitts and Nevis" },
  { id: 121, code: "KP", name: "North Korea" },
  { id: 122, code: "KR", name: "South Korea" },
  { id: 123, code: "KW", name: "Kuwait" },
  { id: 124, code: "KY", name: "Cayman Islands" },
  { id: 125, code: "KZ", name: "Kazakhstan" },
  { id: 126, code: "LA", name: "Laos" },
  { id: 127, code: "LB", name: "Lebanon" },
  { id: 128, code: "LC", name: "Saint Lucia" },
  { id: 129, code: "LI", name: "Liechtenstein" },
  { id: 130, code: "LK", name: "Sri Lanka" },
  { id: 131, code: "LR", name: "Liberia" },
  { id: 132, code: "LS", name: "Lesotho" },
  { id: 133, code: "LT", name: "Lithuania" },
  { id: 134, code: "LU", name: "Luxembourg" },
  { id: 135, code: "LV", name: "Latvia" },
  { id: 136, code: "LY", name: "Libya" },
  { id: 137, code: "MA", name: "Morocco" },
  { id: 138, code: "MC", name: "Monaco" },
  { id: 139, code: "MD", name: "Moldova" },
  { id: 140, code: "ME", name: "Montenegro" },
  { id: 141, code: "MF", name: "Saint Martin" },
  { id: 142, code: "MG", name: "Madagascar" },
  { id: 145, code: "ML", name: "Mali" },
  { id: 146, code: "MM", name: "Myanmar" },
  { id: 147, code: "MN", name: "Mongolia" },
  { id: 148, code: "MO", name: "Macao" },
  { id: 150, code: "MQ", name: "Martinique" },
  { id: 151, code: "MR", name: "Mauritania" },
  { id: 152, code: "MS", name: "Montserrat" },
  { id: 153, code: "MT", name: "Malta" },
  { id: 154, code: "MU", name: "Mauritius" },
  { id: 155, code: "MV", name: "Maldives" },
  { id: 156, code: "MW", name: "Malawi" },
  { id: 157, code: "MX", name: "Mexico" },
  { id: 158, code: "MY", name: "Malaysia" },
  { id: 159, code: "MZ", name: "Mozambique" },
  { id: 160, code: "NA", name: "Namibia" },
  { id: 161, code: "NC", name: "New Caledonia" },
  { id: 162, code: "NE", name: "Niger" },
  { id: 163, code: "NF", name: "Norfolk Island" },
  { id: 164, code: "NG", name: "Nigeria" },
  { id: 165, code: "NI", name: "Nicaragua" },
  { id: 166, code: "NL", name: "Netherlands" },
  { id: 167, code: "NO", name: "Norway" },
  { id: 168, code: "NP", name: "Nepal" },
  { id: 169, code: "NR", name: "Nauru" },
  { id: 170, code: "NU", name: "Niue" },
  { id: 171, code: "NZ", name: "New Zealand" },
  { id: 172, code: "OM", name: "Oman" },
  { id: 173, code: "PA", name: "Panama" },
  { id: 174, code: "PE", name: "Peru" },
  { id: 175, code: "PF", name: "French Polynesia" },
  { id: 176, code: "PG", name: "Papua New Guinea" },
  { id: 177, code: "PH", name: "Philippines" },
  { id: 178, code: "PK", name: "Pakistan" },
  { id: 179, code: "PL", name: "Poland" },
  { id: 180, code: "PM", name: "Saint Pierre and Miquelon" },
  { id: 181, code: "PN", name: "Pitcairn" },
  { id: 182, code: "PR", name: "Puerto Rico" },
  { id: 183, code: "PS", name: "Palestine" },
  { id: 184, code: "PT", name: "Portugal" },
  { id: 185, code: "PW", name: "Palau" },
  { id: 186, code: "PY", name: "Paraguay" },
  { id: 187, code: "QA", name: "Qatar" },
  { id: 188, code: "RE", name: "Réunion" },
  { id: 189, code: "RO", name: "Romania" },
  { id: 190, code: "RS", name: "Serbia" },
  { id: 191, code: "RU", name: "Russia" },
  { id: 192, code: "RW", name: "Rwanda" },
  { id: 193, code: "SA", name: "Saudi Arabia" },
  { id: 194, code: "SB", name: "Solomon Islands" },
  { id: 195, code: "SC", name: "Seychelles" },
  { id: 196, code: "SD", name: "Sudan" },
  { id: 197, code: "SE", name: "Sweden" },
  { id: 198, code: "SG", name: "Singapore" },
  { id: 200, code: "SI", name: "Slovenia" },
  { id: 202, code: "SK", name: "Slovakia" },
  { id: 204, code: "SM", name: "San Marino" },
  { id: 205, code: "SN", name: "Senegal" },
  { id: 206, code: "SO", name: "Somalia" },
  { id: 207, code: "SR", name: "Suriname" },
  { id: 208, code: "SS", name: "South Sudan" },
  { id: 210, code: "SV", name: "El Salvador" },
  { id: 215, code: "TD", name: "Chad" },
  { id: 217, code: "TG", name: "Togo" },
  { id: 218, code: "TH", name: "Thailand" },
  { id: 219, code: "TJ", name: "Tajikistan" },
  { id: 220, code: "TK", name: "Tokelau" },
  { id: 221, code: "TL", name: "Timor-Leste" },
  { id: 222, code: "TM", name: "Turkmenistan" },
  { id: 223, code: "TN", name: "Tunisia" },
  { id: 224, code: "TO", name: "Tonga" },
  { id: 225, code: "TR", name: "Turkey" },
  { id: 226, code: "TT", name: "Trinidad and Tobago" },
  { id: 227, code: "TV", name: "Tuvalu" },
  { id: 228, code: "TW", name: "Taiwan" },
  { id: 229, code: "TZ", name: "Tanzania" },
  { id: 230, code: "UA", name: "Ukraine" },
  { id: 231, code: "UG", name: "Uganda" },
  { id: 233, code: "US", name: "United States" },
  { id: 234, code: "UY", name: "Uruguay" },
  { id: 235, code: "UZ", name: "Uzbekistan" },
  { id: 236, code: "VA", name: "Holy See" },
  { id: 237, code: "VC", name: "Saint Vincent and the Grenadines" },
  { id: 238, code: "VE", name: "Venezuela" },
  { id: 241, code: "VN", name: "Vietnam" },
  { id: 242, code: "VU", name: "Vanuatu" },
  { id: 243, code: "WF", name: "Wallis and Futuna" },
  { id: 244, code: "WS", name: "Samoa" },
  { id: 245, code: "YE", name: "Yemen" },
  { id: 246, code: "YT", name: "Mayotte" },
  { id: 247, code: "ZA", name: "South Africa" },
  { id: 248, code: "ZM", name: "Zambia" },
  { id: 249, code: "ZW", name: "Zimbabwe" },
];

export const unShippableCountries = [
  "Afghanistan",
  "Argentina",
  "Belize",
  "Cuba",
  "Djibouti",
  "El Salvador",
  "Guernsey",
  "Guatemala",
  "Iran",
  "Iraq",
  "Jersey",
  "Jordan",
  "Kyrgyzstan",
  "Kosovo",
  "Lebanon",
  "Liberia",
  "Libya",
  "Marshall Islands",
  "Micronesia",
  "North Korea",
  "North Macedonia",
  "Northern Maria Island",
  "Russia",
  "Samoa",
  "Somalia",
  "South Africa",
  "South Sudan",
  "State of Palestine",
  "Sudan",
  "Syria",
  "Ukraine",
  "Uruguay",
  "Virgin Islands",
  "Yemen",
];

export const USstates = [
  { name: "Alabama", code: "AL" },
  { name: "Alaska", code: "AK" },
  { name: "Arizona", code: "AZ" },
  { name: "Arkansas", code: "AR" },
  { name: "California", code: "CA" },
  { name: "Colorado", code: "CO" },
  { name: "Connecticut", code: "CT" },
  { name: "Delaware", code: "DE" },
  { name: "Florida", code: "FL" },
  { name: "Georgia", code: "GA" },
  { name: "Hawaii", code: "HI" },
  { name: "Idaho", code: "ID" },
  { name: "Illinois", code: "IL" },
  { name: "Indiana", code: "IN" },
  { name: "Iowa", code: "IA" },
  { name: "Kansas", code: "KS" },
  { name: "Kentucky", code: "KY" },
  { name: "Louisiana", code: "LA" },
  { name: "Maine", code: "ME" },
  { name: "Maryland", code: "MD" },
  { name: "Massachusetts", code: "MA" },
  { name: "Michigan", code: "MI" },
  { name: "Minnesota", code: "MN" },
  { name: "Mississippi", code: "MS" },
  { name: "Missouri", code: "MO" },
  { name: "Montana", code: "MT" },
  { name: "Nebraska", code: "NE" },
  { name: "Nevada", code: "NV" },
  { name: "New Hampshire", code: "NH" },
  { name: "New Jersey", code: "NJ" },
  { name: "New Mexico", code: "NM" },
  { name: "New York", code: "NY" },
  { name: "North Carolina", code: "NC" },
  { name: "North Dakota", code: "ND" },
  { name: "Ohio", code: "OH" },
  { name: "Oklahoma", code: "OK" },
  { name: "Oregon", code: "OR" },
  { name: "Pennsylvania", code: "PA" },
  { name: "Rhode Island", code: "RI" },
  { name: "South Carolina", code: "SC" },
  { name: "South Dakota", code: "SD" },
  { name: "Tennessee", code: "TN" },
  { name: "Texas", code: "TX" },
  { name: "Utah", code: "UT" },
  { name: "Vermont", code: "VT" },
  { name: "Virginia", code: "VA" },
  { name: "Washington", code: "WA" },
  { name: "West Virginia", code: "WV" },
  { name: "Wisconsin", code: "WI" },
  { name: "Wyoming", code: "WY" },
];

export const CanadianProvinces = [
  { name: "Alberta", code: "AB" },
  { name: "British Columbia", code: "BC" },
  { name: "Manitoba", code: "MB" },
  { name: "New Brunswick", code: "NB" },
  { name: "Newfoundland", code: "NL" },
  { name: "Northwest Territories", code: "NT" },
  { name: "Nova Scotia", code: "NS" },
  { name: "Nunavut", code: "NU" },
  { name: "Ontario", code: "ON" },
  { name: "Prince Edward Island", code: "PE" },
  { name: "Quebec", code: "QC" },
  { name: "Saskatchewan", code: "SK" },
  { name: "Yukon Territory", code: "YT" },
];
